# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en

title: Zebra Blog
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  'This is a Blog about #CTFs, #WriteUps, #Pen-Testing and #Programming.'
baseurl: #"https://zebra777.github.io" # the subpath of your site, e.g. /blog
url: "https://zebra777.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  zebra777

# Build settings
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed

hydejack:
   dark_mode: 
     dynamic: false
     sunrise: 6
     sunset:  18
     icon:    true
     always:  true

#font: Noto Sans, Helvetica, Arial, sans-serif
#font_heading: Roboto Slab, Helvetica, Arial, sans-serif
#google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

menu:
  - title:             Write Up
    url:               /writeup/
  - title:             Resources
    url:               /tools/
  - title:             Cheat Sheet
    url:               /cheatsheet/
  - title:             Archive
    url:               /archive/ 
  - title:             Following Blogs
    url:               /blogs/   
  - title:             About
    url:               /about/

# Add links to the footer.
# Typically you'll want to link to your cookie- or privacy policy (if appliable), etc..
legal:
  - title:             Github
    url:               https://github.com/Zebra777
  - title:             Discord
    url:               https://discord.gg/4V8xu2
  - title:             Tryhackme
    url:               https://tryhackme.com/p/zebra

copyright:             © 2020. Zebra. All rights reserved.

keywords:              [hacking,programming,ctf,writeup,ethical hacking,whitehat,pen-testing]

logo:                  /assets/img/logo.png

permalink:             /:categories/:title/


author:
  social:
    github:  zebra777 # now github appears first

# Sidebar image and theme color of the site.
accent_image:          /assets/img/sidebar-bg.jpg
accent_color:          rgb(79,177,186)

# This is used for the `theme-color` meta tag,
# which changes the background color of the browser UI in certain browsers.
# Defaults to `accent_color`.
theme_color:           rgb(8,46,57)

# The string encoding which fonts to fetch from Google Fonts.
# See: <https://hydejack.com/docs/configuration/>
google_fonts:          Roboto+Slab:700|Noto+Sans:400,400i,700,700i

# The text font. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font:                  Noto Sans, Helvetica, Arial, sans-serif

# The font used for headings. Expects a string that is a valid CSS font-family value.
# To change font-weight, see _sass/variables.scss
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif

# The font used for code blocks. Expects a string that is a valid CSS font-family value.
font_code:             Fira Code, Menlo, Monaco, Consolas, monospace;

# Hydejack Settings
# ----------------------------------------------------------------------------------------
# These settings are specific to Hydejack.


hydejack:
  # Configure the order of complementary content on blog posts
  post_addons:         [about, newsletter, related, random, comments]

  # Configure the order of complementary content on project pages
  project_addons:      [about, newsletter, other, comments]

  # Set to `true` if you don't want to show an icon indicating external links
  no_mark_external:    false

  # Set to `true` if third party plugins fail to work with dynamically loaded pages
  no_push_state:       false

  # Set to `true` if you want to disable the drawer
  no_drawer:           false

  # Set to `true` if you don't to use the auto-hiding (JavaScript based) navbar.
  # Note that this will not hide the navbar completely, only replace it with a static one.
  # Use custom css to hide completely, e.g. `#_navbar { display: none }`.
  no_navbar:           false

  # Set to true to disable the built-in search functionality.
  # Note that search is disabled during local use to save on build time.
  # Run Jekyll with the `JEKYLL_ENV` environment variable set to `production` to enable.
  no_search:           false

  # Set to `true` if you do not want parts of the css inlined in <head/>
  # This will increase site build speed dramatically!
  no_inline_css:       false

  # Set to `true` if you don't intend on changing the accent color on a per-page basis. 
  # This will increase site build speed!
  no_page_style:       false

  # Code blocks and tables "break" the layout by spanning the full available width.
  # Set this to true if you want them to be the same width as other content.
  no_break_layout:     true

  # Set to `true` to disable the dynamic Table of Contents on large screens.
  no_toc:              false

  # When set to `true`, will not extend the content in the "third column" on large screens.
  # Instead, all content will remains within the center column.
  # Note that this will not affect the Table of Contents, use `no_toc` instead.
  no_third_column:     false

  # Set to `true` if you don't like oversized headlines on large screens.
  no_large_headings:   false

  # Set to `true` if you do not want to expose your resume and projects
  # in machine-readable formats.
  no_structured_data:  false

  # You can set this to `true` if you don't want to set the `theme-color` meta tag,
  # This only affects the meta tag, not the color specified in the app manifest.
  no_theme_color:      false

  # Set to `true` when building with the `--lsi` option
  use_lsi:             true

  # When using Google Analytics, set to `true` to display a cookie notice banner.
  # When enabled, no user-related data will be stored until the user gives consent.
  cookies_banner:      true

  # Set to `true` if you would like to add a "Powered by Hydejack" link in the footer.
  # Note that this setting has no effect when using the free version.
  advertise:           true

  # Buyers of the PRO version can opt to hide all dates from the theme.
  # Frequent consumers of online content will know that nothing devalues a post like
  # seeing an old date. 
  hide_dates:          true

  # Note that dark mode only works in the PRO version of Hydejack.
  dark_mode:
    # Set to `true` to always use the dark theme.
    always:            true

    # Set to `true` to use the dark theme based on visitors' preference (OS setting).
    dynamic:           true

    # Set to `true` to allow visitors to switch between light and dark mode.
    icon:              true
  # ⚡️ DANGER ZONE ⚡️
  # ----------------
  # This is an _experimental_ feature.
  # Only use if you know what Service Workers are and how they can impact your site!
  offline:
    enabled:           false
    cache_version:     7
    precache_assets:
      - /assets/img/swipe.svg


